name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.1
        with:
          submodules: 'recursive'
          ref: ${{ github.head_ref }}
      - name: Set up Node.js
        uses: actions/setup-node@v2.7.2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - name: Build and deploy
        run: npm run deploy
